apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dzxgfe479-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dzxgfe479-python 
  name: dzxgfe479-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dzxgfe479-python 
